name = "family-tree-web"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "family-tree-db"
database_id = "c6a81b20-aeb7-4468-8513-48449e73bc17"

[[r2_buckets]]
binding = "R2"
bucket_name = "family-tree-images"

[vars]
NEXT_PUBLIC_R2_PUBLIC_URL = "https://images.your-domain.workers.dev"
