#!/usr/bin/env python3
"""
Import family tree data from data.xlsx into a D1-compatible SQL file.

Usage:
    pip install openpyxl
    python3 scripts/import_from_excel.py

Reads:  ../data.xlsx   (relative to this script's directory)
Writes: ../migrations/0002_import.sql
"""

import os
import sys

try:
    import openpyxl
except ImportError:
    print("ERROR: openpyxl is not installed. Run: pip install openpyxl")
    sys.exit(1)

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.dirname(SCRIPT_DIR)
EXCEL_PATH = os.path.join(os.path.dirname(ROOT_DIR), "family-tree", "data.xlsx")
OUTPUT_PATH = os.path.join(ROOT_DIR, "migrations", "0002_import.sql")

# ────────────────────────────────────────────────────────────────────────────
# Helpers
# ────────────────────────────────────────────────────────────────────────────

def esc(value) -> str:
    """Escape a value for SQL: return NULL for None/empty, else quoted string."""
    if value is None:
        return "NULL"
    s = str(value).strip()
    if s == "":
        return "''"
    # Escape single quotes
    s = s.replace("'", "''")
    return f"'{s}'"

def safe_str(value) -> str:
    """Convert to string, stripping whitespace; return '' for None."""
    if value is None:
        return ""
    return str(value).strip()


def read_sheet(wb, sheet_name: str):
    """Return list of dicts for each data row in the sheet (uses first row as headers)."""
    if sheet_name not in wb.sheetnames:
        print(f"  WARNING: Sheet '{sheet_name}' not found — skipping.")
        return []
    ws = wb[sheet_name]
    rows = list(ws.iter_rows(values_only=True))
    if not rows:
        return []
    headers = [str(h).strip() if h is not None else f"col_{i}" for i, h in enumerate(rows[0])]
    result = []
    for row in rows[1:]:
        d = {headers[i]: (row[i] if i < len(row) else None) for i in range(len(headers))}
        result.append(d)
    return result


# ────────────────────────────────────────────────────────────────────────────
# Main
# ────────────────────────────────────────────────────────────────────────────

def main():
    if not os.path.exists(EXCEL_PATH):
        print(f"ERROR: Excel file not found at {EXCEL_PATH}")
        sys.exit(1)

    print(f"Reading {EXCEL_PATH} …")
    wb = openpyxl.load_workbook(EXCEL_PATH, data_only=True)

    print(f"Sheets found: {wb.sheetnames}")

    # Read all sheets
    main_rows   = read_sheet(wb, "Main")
    image_rows  = read_sheet(wb, "images")
    link_rows   = read_sheet(wb, "links")
    gdrive_rows = read_sheet(wb, "gdrives")

    # Build image lookup: person_id -> image_url
    image_map: dict[str, str] = {}
    for row in image_rows:
        pid = safe_str(row.get("person"))
        img = safe_str(row.get("image"))
        if pid and img:
            image_map[pid] = img

    statements: list[str] = []
    statements.append("-- Auto-generated by scripts/import_from_excel.py")
    statements.append("-- Do not edit manually — re-run the script to regenerate.\n")

    # ── PEOPLE & SPOUSES ────────────────────────────────────────────────────
    people_ids: set[str] = set()
    spouse_statements: list[str] = []

    statements.append("-- People")

    GENERATION_PLACEHOLDERS = {
        "Generation_1", "Generation_2", "Generation_3",
        "Generation_4", "Generation_5", "Generation_6",
    }

    for row in main_rows:
        person_id   = safe_str(row.get("person"))
        full_name   = safe_str(row.get("person_full"))
        parent_id   = safe_str(row.get("parent"))
        tooltip     = safe_str(row.get("tooltip"))
        spouse_id   = safe_str(row.get("spouse"))
        spouse_full = safe_str(row.get("spouse_full"))

        if not person_id:
            continue

        # Skip pure generation placeholder rows but keep them as minimal nodes
        # if they are referenced as parents (needed for tree structure)
        is_placeholder = person_id in GENERATION_PLACEHOLDERS

        img_url = image_map.get(person_id, "")

        people_ids.add(person_id)

        stmt = (
            f"INSERT OR IGNORE INTO people (id, full_name, parent_id, tooltip, image_url, status) VALUES ("
            f"{esc(person_id)}, "
            f"{esc(full_name) if full_name else esc(person_id)}, "
            f"{esc(parent_id) if parent_id else 'NULL'}, "
            f"{esc(tooltip)}, "
            f"{esc(img_url)}, "
            f"'{'hidden' if is_placeholder else 'approved'}'"
            f");"
        )
        statements.append(stmt)

        # Spouse entry
        if spouse_id and spouse_full:
            spouse_img = image_map.get(spouse_id, "")
            s_stmt = (
                f"INSERT OR IGNORE INTO spouses (id, full_name, person_id, image_url) VALUES ("
                f"{esc(spouse_id)}, "
                f"{esc(spouse_full)}, "
                f"{esc(person_id)}, "
                f"{esc(spouse_img)}"
                f");"
            )
            spouse_statements.append(s_stmt)

    if spouse_statements:
        statements.append("\n-- Spouses")
        statements.extend(spouse_statements)

    # ── LINKS ────────────────────────────────────────────────────────────────
    if link_rows:
        statements.append("\n-- Links")
        for row in link_rows:
            pid  = safe_str(row.get("person"))
            url  = safe_str(row.get("link"))
            desc = safe_str(row.get("description"))
            if not pid or not url:
                continue
            stmt = (
                f"INSERT INTO links (person_id, url, description, display_html) VALUES ("
                f"{esc(pid)}, {esc(url)}, {esc(desc)}, {esc(desc)}"
                f");"
            )
            statements.append(stmt)

    # ── GALLERIES ────────────────────────────────────────────────────────────
    if gdrive_rows:
        statements.append("\n-- Galleries")
        for order, row in enumerate(gdrive_rows):
            desc = safe_str(row.get("description"))
            link = safe_str(row.get("link"))
            if not desc or not link:
                continue
            stmt = (
                f"INSERT INTO galleries (description, gdrive_link, display_order) VALUES ("
                f"{esc(desc)}, {esc(link)}, {order}"
                f");"
            )
            statements.append(stmt)

    # ── Write output ─────────────────────────────────────────────────────────
    sql = "\n".join(statements) + "\n"
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write(sql)

    print(f"\nWrote {len(statements)} SQL statements to {OUTPUT_PATH}")
    print("\nNext steps:")
    print("  npm run import:local   # load into local D1 dev database")
    print("  npm run import:remote  # load into production D1 database")


if __name__ == "__main__":
    main()
